name: api
'on':
  push: null
  schedule:
    - cron: 0 5 2-31/2 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm:install'
          run: npm install
          env:
            CI: true
      - name: deploye
        run: npm run deploye
